# Generated by Django 4.1 on 2022-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('purple', 'purple')], max_length=100),
        ),
    ]
